# Tensors

In [3]:
from sys import version
import torch
import numpy as np

print(f'python:\n{version}')
print(f'torch: {torch.__version__}')

if torch.backends.mps.is_available():
    print('mps is available')
    torch.device('mps')

python:
3.8.13 (default, Mar 28 2022, 06:13:39) 
[Clang 12.0.0 ]
torch: 1.12.1
mps is available


In [4]:
# listからデータ作れるよ
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(f'generate tensor from list:\n{x_data}')

generate tensor from list:
tensor([[1, 2],
        [3, 4]])


In [5]:
# numpy からも作れるよ
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(f'generate tensor from np:\n{x_np}')

generate tensor from np:
tensor([[1, 2],
        [3, 4]])


In [6]:
# npみたいに，1だけのtensorとかrandomな値をもつtensorも作れるよ
x_ones = torch.ones_like(x_data)
print(f'ones tensor:\n{x_ones}')
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(f'rand tensor:\n{x_rand}')

ones tensor:
tensor([[1, 1],
        [1, 1]])
rand tensor:
tensor([[0.3353, 0.9901],
        [0.5036, 0.6659]])


In [8]:
# shape指定
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

In [9]:
# attributes
tensor = torch.rand(3, 4)
print(f'shape: {tensor.shape}')  # ただのtupleではない
print(f'dtype: {tensor.dtype}')
print(f'device tensor is stored on: {tensor.device}')

shape: torch.Size([3, 4])
dtype: torch.float32
device tensor is stored on: cpu


In [12]:
# 大きいtensorをdevice間でやり取りすると時間とメモリがかかるとのこと
if torch.backends.mps.is_available():
    tensor = tensor.to('mps')
print(f'device tensor is stored on: {tensor.device}')

# 要素アクセスとスライシング
tensor = torch.ones(4, 4)
tensor[:, 1] = 0  # 1列目を0とする
print(f'first row: {tensor[0]}')
print(f'first col: {tensor[:, 0]}')
print(f'last  col: {tensor[..., -1]}')

device tensor is stored on: mps:0
first row: tensor([1., 0., 1., 1.])
first col: tensor([1., 1., 1., 1.])
last  col: tensor([1., 1., 1., 1.])


In [14]:
# concat
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(f'concat:\n{t1}')

concat:
tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [19]:
# mul
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

for i, y in enumerate([y1, y2, y3]):
    print(f'y{i}:\n{y}')

y0:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y1:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
y2:
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])


In [20]:
# element-wise product

z1 = tensor * tensor
z2 = tensor.mul(tensor.T)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

for i, z in enumerate([z1, z2, z3]):
    print(f'z{i}:\n{z}')

z0:
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z1:
tensor([[1., 0., 1., 1.],
        [0., 0., 0., 0.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])
z2:
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


In [26]:
# 要約と取り出し
agg = tensor.sum()
print(f'sum of tensor: {agg}({type(agg)})')
agg_item = agg.item()
print(f'sum of tensor: {agg_item}({type(agg_item)})')

ave = tensor.mean()
print(f'mean of tensor: {ave}({type(ave)})')

sum of tensor: 12.0(<class 'torch.Tensor'>)
sum of tensor: 12.0(<class 'float'>)
mean of tensor: 0.75(<class 'torch.Tensor'>)


In [32]:
# numpyとの変換ができる
# このとき，対象のtensorはCPU上にあること

t = torch.ones(5)
print(f't({type(t)}:\n{t}')

n = t.numpy()
print(f'n({type(n)}:\n{n}')

# 参照関係があるため，tへの変更はnに反映される点を覚えておく
t.add_(1)

print(f't({type(t)}:\n{t}')
print(f'n({type(n)}:\n{n}')

t(<class 'torch.Tensor'>:
tensor([1., 1., 1., 1., 1.])
n(<class 'numpy.ndarray'>:
[1. 1. 1. 1. 1.]
t(<class 'torch.Tensor'>:
tensor([2., 2., 2., 2., 2.])
n(<class 'numpy.ndarray'>:
[2. 2. 2. 2. 2.]
